chore(deps): update dependency versions 31

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -45,37 +45,95 @@ jobs:
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
-      - name: Configure Git
+      - name: "Get previous version from npm"
         run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/dharmesh-r-patel/react-monorepo.git
-          git pull --rebase origin main
+           echo "$(npm view your-package-name version)" > .version
 
-      - name: Fetch and Clean Remote Tags
-        run: |
-          git fetch --tags --force
-          git tag -d $(git tag -l) || true
-          git fetch --tags
-
-      - name: Test Git Authentication
-        run: |
-          git ls-remote https://x-access-token:${{ secrets.GH_PAT }}@github.com/dharmesh-r-patel/react-monorepo.git
-
-      - name: "Version and publish"
-        run: |
-          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
-            lerna version --conventional-commits --conventional-graduate --yes
-          else
-            lerna version --conventional-commits --conventional-prerelease --preid beta --yes
-          fi
 
       - name: Publish Packages
         run: |
-          # lerna publish from-git --yes --loglevel verbose || (echo "Publish failed! Reverting..." && git reset --hard HEAD~1)
-          lerna publish from-package -y --no-verify-access
+          lerna publish --conventional-commits --no-git-tag-version --yes
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+# name: Publish Packages
+
+# on:
+#   push:
+#     branches:
+#       - main
+#   pull_request:
+#     branches:
+#       - main      
+#   workflow_dispatch:
+
+# jobs:
+#   build-and-publish:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Checkout Repository
+#         uses: actions/checkout@v4
+#         with:
+#           fetch-depth: 0  # Ensure full history for versioning
+
+#       - name: Setup Node.js
+#         uses: actions/setup-node@v4
+#         with:
+#           node-version: '20.x'
+#           registry-url: 'https://registry.npmjs.org/'
+
+#       - name: Setup Yarn
+#         run: yarn set version stable
+
+#       - name: Install Dependencies
+#         run: yarn install --immutable
+
+#       - name: Build Packages
+#         run: yarn build
+
+#       - name: Setup .npmrc
+#         run: |
+#           echo "registry=https://registry.npmjs.org/" > ~/.npmrc
+#           echo "@infineit:registry=https://registry.npmjs.org/" >> ~/.npmrc
+#           echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
+
+#       - name: Verify npm authentication
+#         run: npm whoami
+#         env:
+#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+
+#       - name: Configure Git
+#         run: |
+#           git config --global user.name "github-actions[bot]"
+#           git config --global user.email "github-actions[bot]@users.noreply.github.com"
+#           git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/dharmesh-r-patel/react-monorepo.git
+#           git pull --rebase origin main
+
+#       - name: Fetch and Clean Remote Tags
+#         run: |
+#           git fetch --tags --force
+#           git tag -d $(git tag -l) || true
+#           git fetch --tags
+
+#       - name: Test Git Authentication
+#         run: |
+#           git ls-remote https://x-access-token:${{ secrets.GH_PAT }}@github.com/dharmesh-r-patel/react-monorepo.git
+
+#       - name: "Version and publish"
+#         run: |
+#           if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
+#             lerna version --conventional-commits --conventional-graduate --yes
+#           else
+#             lerna version --conventional-commits --conventional-prerelease --preid beta --yes
+#           fi
+
+#       - name: Publish Packages
+#         run: |
+#           # lerna publish from-git --yes --loglevel verbose || (echo "Publish failed! Reverting..." && git reset --hard HEAD~1)
+#           lerna publish from-package -y --no-verify-access
+#         env:
+#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
 
 # name: Publish Packages
